stages:
  - test
  - build
  - deploy

# 1️⃣ Run tests
test:
  stage: test
  image: node:20
  script:
    - npm install
    - npm test

# 2️⃣ Build Docker image
build:
  stage: build
  image: docker:20
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/<your-username>/<repo>:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.gitlab.com/<your-username>/<repo>:latest

# 3️⃣ Deploy
deploy:
  stage: deploy
  image: hashicorp/terraform:1.5.7
  script:
    - terraform init
    - terraform apply -auto-approve
  environment:
    name: production
    url: http://<your-ec2-public-ip>
